### PR TITLE
Fixing an error in getUnitsAround

### PR DESCRIPTION
**Pull request by andertavares**
The method was actually checking if the unit was within some distance from the given top-left coordinate. Now it checks if the unit is really inside the area. In other words, if x,y are the top left of the rectangle with a given width and height, the method checks if x <= unitX < x+width && y <= unitY < y+height.

My bad for doing it wrong on the first time.

### CODE REVIEW

**Comment by santiontanon** [comment]
Oh! Thanks for noticing this! But the fix should go the other way around. What was wrong with that function is the description of what it does, not the code. The old code was correct, as this function is used by the WorkerRush, LightRush, etc. to find units "around" a center point. So, what it does is given a center point, width and height, get all the units that are less than "width" and "height" distance from the center point. So, again, the old implementation was the correct one. What has to be fixed is the comment.

**Comment by santiontanon** [comment]
Wait, let me take my comment back! I got confused. It's not LightRush, WorkerRush, etc. that use this function, but EconomyMilitaryRush, EconomyRush, etc. In any case, are you sure that x, y are the top-left coordinate, and not the center? from the way the functions are used it seems that x, y should be the center and that the old implementation was correct, just with the wrong in-line comment, no?

**Comment by andertavares** [comment]
You are correct. The function code gets units around a central point, so the comment is wrong, not the code.

Would it be a good idea to close this PR and open another one fixing the comment, plus adding a function to get units within a rectangle (specified by top-left coordinate, width & height), which would use the code of this PR?

**Comment by santiontanon** [comment]
Yeah, that would be great! In that way we have both functionalities :)

**Comment by andertavares** [comment]
Ok, I'll close this one and open a new with the corrections.

**Pull request closed without merging**
