### PR TITLE
Migrate to gradle

### PR DESCRIPTION
**Pull request by scheffield**
This PR does the bare minimum to migrate the project to `gradle`. This should ease the initial setup  for people new to the project and simplify future maintenance.

Running the application becomes as simple as executing

```bash
./gradlew run
```

This will
1. Download the currently configured version of `gralde` ([gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html))
2. Build the application
3. Run `rts.MicroRTS` ([application plugin](https://docs.gradle.org/current/userguide/application_plugin.html))

As mentioned before this is only a minimal migration. There are additional things that should be done in subsequent PRs. For example:
* Seperate test code into `src/test/java`
* Move from file based dependencies (in `lib/*.jar`) to maven central
* Apply a more appropriate namespace like `org.santiontanon.microrts`

I'm more than happy to create follow up PRs but would wait until the current one was accepted and merged.

### CODE REVIEW

**Comment by santiontanon** [comment]
Thanks for the pull request. I'm a bit hesitant on this though, as I don't like making projects depend on other things. Would this make the project "depend" on Gradle or Maven? (no idea what either is btw :)). If it does, then I'd be sorry to say that I would not accept it. But if it's just giving an option to use those services (Again, not sure what they are), but not forcing them, then I'd definitively consider it!

**Comment by douglasrizzo** [comment]
The project already depends on weka, minimal-json, jdom and junit (the last one is not present in the lib directory, btw).

Instead, you can make the project depend on either Gradle or Maven, which are tools that automatically download these other libraries and build the project for the user. One of the advantages is that you wouldn't need to ship the project with the jar files inside the lib directory anymore.

**Comment by santiontanon** [comment]
Notice that the project does NOT depend on those packages, as JAR files for them are included in this repo. Even if those projects (Weka, jdom, etc.) die and are not maintained any further, or they change the API, etc. microRTS will keep working. I included the jar files on purpose, rather than having people get those dependencies on their own, precisely to ensure that microRTS did NOT depend on any external packages. I have had plenty of bad experiences in the past with projects depending on external resources, and APIs changing, etc. making my projects unusable. So, I hope you understand I do not want any dependencies that might force me to update the project or else let it die if the dependencies change/stop being maintained.

So, I just want to ask the same question: if I accept this pull request, will microRTS depend on Gradle or Maven? if it does, then I cannot accept it. But if it's just an optional thing that if any users of Maven want they can use, but does not affect anyone else, then sure! If it creates a dependency, then my suggestion is to clone this repo into another one that can be made depend on Gradle if that's easier to some people. But leave this one as is.

**Comment by douglasrizzo** [comment]
They won't become dependencies of microRTS and it will still be possible to build and execute the program without them.

However, these management tools expect the Java project to follow a standard structure (as was described in #19), so source files, test files and resource files would need to be moved. This was partially done for this pull request on commit https://github.com/santiontanon/microrts/pull/48/commits/43a33688cf23fc7c2bb6b56289001c79168cc9a2. The instructions to build and run microRTS without Gradle or Maven would need to be updated to reflect the change in directory structure.

The existent JAR files could still be linked from the `lib` directory, but all the current dependencies of microRTS are available in the [Maven Repository](https://mvnrepository.com/), which is maintained by Apache. Gradle and Maven can download them automatically in the same way that Python packages download their dependencies from [Pypi](https://pypi.org/). You can specify the version of each library, so API changes won't be a problem.

**Comment by santiontanon** [comment]
Oh, missed the folder restructuring. I apologize, but I am going to decline this pull request then. It'll break too many things, and other projects currently depending on this one. If we ever work on microRTS2 from a clean slate, I'll consider this though, so thanks for the proposal!

**Pull request closed without merging**
